# Generated by Django 3.0.3 on 2020-02-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='myscreens/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
