# Generated by Django 3.0.3 on 2020-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myscreen',
            name='img_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
