# Generated by Django 3.0.3 on 2020-02-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshots', '0002_myscreen_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myscreen',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='myscreens/'),
        ),
        migrations.AlterField(
            model_name='myscreen',
            name='img_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
