# Generated by Django 3.0.3 on 2020-02-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshots', '0003_auto_20200223_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myscreen',
            name='img_name',
        ),
    ]
